web-data-visualisation/retina/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='retina-home'),
    path('about/', views.about, name='retina-about'),
    path('exp/<int:pk>/', views.create_exp_view, name='exp_with_pk'),
    # path('<int:pk>/', views.DataUpdateView.as_view(), name='data_change'),
    path('ajax/load-pxmy/', views.load_px_my, name='ajax_load_pxmy'),
    path('ajax/load-dataxxx/', views.load_dataxxx, name='ajax_load_dataxxx'),
    path('ajax/load-pattern/', views.load_pattern_file, name='ajax_load_pattern'),
    path('ajax/load-pattern-number/', views.load_pattern_number, name='ajax_load_pattern_number'),
    path('ajax/plot-png/', views.get_plot, name='ajax_get_plot'),

    path('ajax/plot-pattern-png/', views.get_pattern_plot, name='ajax_get_pattern_plot'),

    path('ajax/movies-pattern/', views.movie_for_pattern, name='ajax_load_movie_for_pattern'),
    path('ajax/movies/', views.movie_numbers, name='ajax_load_movie_number'),

]

web-data-visualisation/web_app_project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from users.forms import LoginForm
from retina import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', form_class=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('retina.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^senddataoutside', views.SendDataOutside)
]

web-data-visualisation/retina/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django import forms
import os


class DataFolder(models.Model):
    dataxxx = models.CharField(max_length=150, blank=True, null=True)
    exp = models.ForeignKey('Experiment', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'data_folder'

    def __str__(self):
        return self.dataxxx


class Experiment(models.Model):
    experimentname = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'experiment'

    def __str__(self):
        return self.experimentname

    def get_name(self):
        if self.experimentname is not None:
            return os.path.basename(self.experimentname)


class RawData(models.Model):
    pattern_number = models.IntegerField(blank=True, null=True)
    px_my = models.CharField(max_length=150, blank=True, null=True)
    pattern_file = models.CharField(max_length=150, blank=True, null=True)
    data = models.ForeignKey(DataFolder, models.DO_NOTHING)
    movie_number = models.IntegerField(null=True)

    def __str__(self):
        return self.px_my

    class Meta:
        managed = False
        db_table = 'raw_data'

web-data-visualisation/retina/forms.py
from django import forms
from .models import RawData, DataFolder

class DataForm(forms.ModelForm):
    class Meta:
        model = RawData
        fields = ('data', 'px_my', 'pattern_file')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['px_my'].queryset = RawData.objects.using('retina').none()


        if 'data' in self.data:
            try:
                data_id = int(self.data.get('data'))
                self.fields['px_my'].queryset = RawData.objects.using('retina').filter(country_id=data_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['px_my'].queryset = self.instance.country.city_set.order_by('name')

web-data-visualisation/retina/views.py
import json
import logging
from collections import defaultdict
from os.path import join

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Experiment, DataFolder, RawData
from .plotting import plot_pxmy_to_bytes, plot_pxmy_and_neighbours, plot_pxmy_without_neighbours

logger = logging.getLogger(__name__)
# rows_in_exp = Experiment.objects.using('retina').all()
# rows_in_data = DataFolder.objects.using('retina').all()
datadict = defaultdict(list)


# for row in rows_in_data:
#     datadict[row.exp.pk].append(row.dataxxx)

@api_view(['POST'])
def SendDataOutside(local_trace):
    print(" local to: ", local_trace)
    print("typ to: ", type(local_trace))
    test_response = [{"long": "19.944", "lat": "50.047"}, {"long": "19.946", "lat": "50.044"},
            {"long": "19.941", "lat": "50.043"}]
    try:
        height = json.loads(local_trace.body)
        print(" local to: ", height)
        print("typ to: ", type(height))

        return JsonResponse(test_response, safe=False)
    except ValueError as e:
        return Response(e.args[0], status.HTTP_400_BAD_REQUEST)


@login_required
def home(request, pk=None):
    # if pk:
    #     exp = Experiment.objects.using('retina').get(pk=pk)
    #
    # expname = [row.experimentname.split('/')[-1] for row in rows_in_exp]
    # expdict = {Experiment.objects.using('retina')[0]: 'exp_with_pk'}
    # expdict.update({Experiment.objects.using('retina')[1]: 'exp_with_pk'})
    # expdict.update({Experiment.objects.using('retina')[2]: 'exp_with_pk'})

    with open(r'C:\HackYEAH_2020\HackYEAH-2020-COVID19\db.json', 'r') as file:
        parsed_json = json.load(file)

    return render(request, 'retina/home_button.html', {'json': parsed_json})



def about(request):
    return render(request, 'retina/about.html', {'title': 'about'})


@login_required
def create_exp_view(request, pk):
    return render(request, 'retina/rawdata_form.html', {'pk': pk})


@login_required
def load_px_my(request):
    data_id = request.GET.get('data_id')
    if data_id is not None and data_id.isdigit():
        pxmy = RawData.objects.using('retina').filter(data_id=data_id).all()
        print('jestem w load_px_my', pxmy)
        return render(request, 'retina/pxmy_dropdown_list_options.html', {'pxmy': pxmy})
    else:
        return HttpResponse('')


@login_required
def load_pattern_number(request):
    data_id = request.GET.get('data_id')
    if data_id is not None and data_id.isdigit():
        pat_num = RawData.objects.using('retina').filter(data_id=data_id).values_list('pattern_number',
                                                                                      flat=True).order_by(
            'pattern_number')
        pat_num = set(pat_num)
        return render(request, 'retina/pattern_number_dropdown_list_options.html', {'pat_num': pat_num})
    else:
        return HttpResponse('')


@login_required
def load_dataxxx(request):
    exp_id = request.GET.get('exp_id')
    dataxxx = DataFolder.objects.using('retina').filter(exp_id=exp_id).all()
    return render(request, 'retina/dataxxx_dropdown_list_options.html', {'dataxxx': dataxxx})


@login_required
def load_pattern_file(request):
    pxmy_id = request.GET.get('pxmy_id')
    pattern = RawData.objects.using('retina').get(id=pxmy_id).pattern_file
    return HttpResponse(pattern)


@login_required
def movie_numbers(request):
    data_id = request.GET.get('data_id')
    if data_id is not None and data_id.isdigit():
        movies = RawData.objects.using('retina').filter(data_id=data_id).values_list('movie_number',
                                                                                     flat=True).distinct().order_by(
            'movie_number')
        print('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n')
        print(movies)
        return render(request, 'retina/movies_dropdown_list_options.html', {'movies': movies})
    else:
        return HttpResponse('')


@login_required
def movie_for_pattern(request):
    pattern_number = request.GET.get('pat_num')
    data_id = request.GET.get('data_id')
    if pattern_number is not None and pattern_number.isdigit():
        movies = RawData.objects.using('retina').filter(pattern_number=pattern_number, data_id=data_id).values_list(
            'movie_number',
            flat=True).distinct().order_by(
            'movie_number')
        return render(request, 'retina/movies_dropdown_list_options.html', {'movies': movies})
    else:
        return HttpResponse('')


@login_required
def get_plot(request):
    response = HttpResponse(content_type='application/png')
    response['Content-Disposition'] = 'attachment; filename="plot.png"'

    electrode_from = int(request.GET.get('electrode_from'))
    electrode_to = int(request.GET.get('electrode_to'))
    movie_number = request.GET.get('movie_number')
    rawdata_id = request.GET.get('rawdata_id')
    data_id = request.GET.get('data_id')

    paths = []

    if movie_number is not None:
        rawdatas = RawData.objects.using('retina').filter(movie_number=int(movie_number), data_id=int(data_id)).all()
        logger.info(f'rawdatas={rawdatas}')
        print(movie_number)
        print(data_id)

        for rawdata in rawdatas:
            dataxxx = DataFolder.objects.using('retina').get(id=rawdata.data_id)
            experim = Experiment.objects.using('retina').get(id=dataxxx.exp_id)
            path = join(experim.experimentname, dataxxx.dataxxx, rawdata.px_my)
            paths.append(path)

    if rawdata_id is not None:
        rawdata = RawData.objects.using('retina').get(id=rawdata_id)
        dataxxx = DataFolder.objects.using('retina').get(id=rawdata.data_id)
        experim = Experiment.objects.using('retina').get(id=dataxxx.exp_id)
        path = join(experim.experimentname, dataxxx.dataxxx, rawdata.px_my)
        paths.append(path)

    print("\n\n\npaths= " + str(paths) + '\n\n\n')
    # TODO marge path via join()
    plot = plot_pxmy_to_bytes(paths, electrode_from, electrode_to)
    response.write(plot)
    return response


@login_required
def get_pattern_plot(request):
    response = HttpResponse(content_type='application/png')
    response['Content-Disposition'] = 'attachment; filename="plot.png"'

    pat_number = request.GET.get('pat_num')
    electrode_to_plot = int(request.GET.get('ele_to_plot'))
    movie_number = int(request.GET.get('movie_number'))
    data_id = request.GET.get('data_id')
    neighbours = request.GET.get('neighbours')

    if not request.GET.get('y_axis_min').strip():
        y_axis_min = None
    else:
        y_axis_min = int(request.GET.get('y_axis_min'))

    if not request.GET.get('y_axis_max').strip():
        y_axis_max = None
    else:
        y_axis_max = int(request.GET.get('y_axis_max'))

    if not request.GET.get('x_axis_min').strip():
        x_axis_min = None
    else:
        x_axis_min = int(request.GET.get('x_axis_min'))

    if not request.GET.get('x_axis_max').strip():
        x_axis_max = None
    else:
        x_axis_max = int(request.GET.get('x_axis_max'))

    selected_path = None

    rawdatas = RawData.objects.using('retina').filter(pattern_number=int(pat_number),
                                                      data_id=int(data_id)).all().order_by(
        'movie_number')

    for rawdata in rawdatas:
        dataxxx = DataFolder.objects.using('retina').get(id=rawdata.data_id)
        experim = Experiment.objects.using('retina').get(id=dataxxx.exp_id)
        if rawdata.movie_number == movie_number:
            selected_path = join(experim.experimentname, dataxxx.dataxxx, rawdata.px_my)

    print(type(neighbours))
    print("print 1 %%%%%%%%%%%%%%%%%%%%%%%", neighbours)
    print('selected path: {selected_path}')
    if neighbours != "false":
        print("print 2 %%%%%%%%%%%%%%%%%%%%%%%", neighbours)
        print('selected path: {selected_path}')
        plot = plot_pxmy_and_neighbours([selected_path], electrode_to_plot, movie_number, y_axis_min=y_axis_min,
                                        y_axis_max=y_axis_max,
                                        x_axis_min=x_axis_min, x_axis_max=x_axis_max)
        response.write(plot)
        return response

    else:
        print("print 3 %%%%%%%%%%%%%%%%%%%%%%%", neighbours)
        print('selected path: {selected_path}')
        plot = plot_pxmy_without_neighbours([selected_path], electrode_to_plot, movie_number, y_axis_min=y_axis_min,
                                            y_axis_max=y_axis_max,
                                            x_axis_min=x_axis_min, x_axis_max=x_axis_max)
        response.write(plot)
        return response

web-data-visualisation/retina/templates/retina/about.html
{% extends 'retina/base.html' %}
{% block content %}
<h1></h1>
<p> <b><font size="5"> Introduction </font></b></p>
    <div>
    One of the most useful elements of data analyzing is visualization. Proper view of big data
    is neccessary to improve the analyzing proccess. <br>Thanks to visualization it is possible to make
    initial selection, evaluate if test was performed as assumed, if nothing perturbed experiment
    or if it is neccessary to perform experiment one more time.
    <br>Main assumption to create this application was to support data analyzing from retina project located
    on local, internal server. Thanks to this website it is possible to create a plot for every raw data in easy and fast way.
    </div>

<br>
<p> <b> <font size="5"> How to use </font> </b></p>
    <div>
        To use application an account is neccessary. Please note that every new account is created as <font color="red">INACTIVE</font> and only administrator
    can authorize it. <br>If you have any problem with authorization or if you have a question please contact one of web administrator:<br>
        <b>Tomasz Szumlak, PhD</b><br>
        <b>Paweł Hottowy, PhD </b>
    </div>
{% endblock content %}

web-data-visualisation/retina/templates/retina/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'retina/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'retina/mano.css' %}">

    {% if title %}
    <title>Retina project - {{ title }}</title>
    {% else %}
    <title>Retina project</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'retina-home' %}">Retina project</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'retina-about' %}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container-full">
    <div>
        <div class="container-div">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block pat_num %}{% endblock %}
        </div>
        <div class="container-div">
            {% block content %}{% endblock %}
        </div>
    </div>
</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

web-data-visualisation/retina/templates/retina/dataxxx_dropdown_list_options.html
<option value="null">---------</option>
{% for el in dataxxx %}
<option value="{{ el.id }}">{{ el.dataxxx }}</option>
{% endfor %}

web-data-visualisation/retina/templates/retina/movies_dropdown_list_options.html
<option value="null">---------</option>
{% for movie in movies %}
<option value="{{ movie }}">{{ movie }}</option>
{% endfor %}

web-data-visualisation/retina/templates/retina/pattern_number_dropdown_list_options.html
<option value="null">---------</option>
{% for el in pat_num %}
<option value="{{ el }}">{{ el }}</option>
{% endfor %}

web-data-visualisation/retina/templates/retina/rawdata_form.html
{% extends 'retina/base.html' %}

{% block pat_num %}

<h2>Plot data for given pattern and movie:</h2>

<div id="single_pattern_plot"  data-pattern-url="{% url 'ajax_load_pattern_number' %}"
                               data-dataxxx-url="{% url 'ajax_load_dataxxx' %}"
                               data-movie-for-pattern-url="{% url 'ajax_load_movie_for_pattern' %}"

     novalidate>
    {% csrf_token %}
    <table>
        <tbody>
        <tr>
            <th><label for="pattern_data">Data:</label></th>
            <td><select name="data" required="" id="pattern_data">
                <option value="null">---------</option>
            </select></td>
        </tr>
        <tr>
            <th><label for="pattern_number">Pattern number:</label></th>
            <td><select name="pattern_number" required="" id="pattern_number">
            </select></td>
            <th><label for="movie_for_pattern">Movie number:</label></th>
            <td><select name="movie_number" required="" id="movie_for_pattern">
            </select></td>
        </tr>
        <tr>
            <th width="50"><label for="electrode_to_plot">Electrode to plot:</label></th>
            <td width="50"><input type="text" name="Electrode to plot" maxlength="5" required="" id="electrode_to_plot"></td>

        </tr>
        <tr>
            <th><label for="x_range_min">X axis min:</label></th>
            <td><input type="text" name="x_range_min" maxlength="5" id="x_range_min"></td>
            <th><label for="x_range_max">X axis max:</label></th>
            <td><input type="text" name="x_range_max" maxlength="5" id="x_range_max"></td>
        </tr>
        <tr>
            <th><label for="y_range_min">Y axis min:</label></th>
            <td><input type="text" name="y_range_min" maxlength="5" id="y_range_min"></td>
            <th><label for="y_range_max">Y axis max:</label></th>
            <td><input type="text" name="y_range_max" maxlength="5" id="y_range_max"></td>
        </tr>
        <tr>
            <th><button id="pattern_plot_button">Plot</button></th>
            <th>
                <button id="previous_plot">Previous Plot</button>
                <button id="next_plot">Next Plot</button>
            <th><button id="matrix">Show matrix</button></th>
        </tr>
        </tbody>
    </table>
    <th colspan="2"><label class="error-msg" id="pattern_error_label"></label></th>

</div>
<div id="divo" class="plot-div">
    <th> <label> Plot neighbours: </label><input type="checkbox" id="neigh"> </th>
    <img id="pattern_plot" class="plot-size">
</div>
<br><br>

<script>
    $("#pattern_plot").click(function(e){
        var pWidth = $(this).innerWidth();
        var pOffset = $(this).offset();
        var x = e.pageX - pOffset.left;
        if(pWidth/3 > x){
            $('#movie_for_pattern option:selected').prev().prop('selected', true);
            plot()
            }
        else if(pWidth/3*2 < x){
            $('#movie_for_pattern option:selected').next().prop('selected', true);
            plot()
            }
        else{
            if($("#neigh").prop("checked")){
                $("#neigh").prop("checked", false)
                plot()
            }
            else{
                $("#neigh").prop("checked", true)
                plot()
            }
        }
    });

    plot = function() {
        var ele_to_plot = $("#electrode_to_plot").val();
        var pat_num = $("#pattern_number").val();
        var data_id = $("#pattern_data").val();
        var movie_number = $("#movie_for_pattern").val();
        var y_axis_min =$("#y_range_min").val();
        var y_axis_max =$("#y_range_max").val();
        var x_axis_min =$("#x_range_min").val();
        var x_axis_max =$("#x_range_max").val();
        var neighbours =$("#neigh").prop("checked");
        $('div#divo').show();

        if (data_id == null || data_id == 'null') {
            $("#pattern_error_label").html("ERROR!: 'Data' is not selected!");
        }

        else if (pat_num == null || pat_num == 'null') {
            $("#pattern_error_label").html("ERROR!: 'Pattern number' is not selected!");
        }

        else if (movie_number == null || movie_number == 'null') {
            $("#pattern_error_label").html("ERROR!: 'Movie number' is not selected!");
        }

        else if (!isNormalInteger(ele_to_plot)){
            $("#pattern_error_label").html("ERROR!: 'Electrode to plot' is not a number!");
        }

        else if (ele_to_plot > 512 || ele_to_plot < 1){ //TODO 512 import from static
            $("#pattern_error_label").html("ERROR!: Electrode to plot out of range. Must be beetween <1, 512>");
        }

        else{
            $("#pattern_error_label").html("");
            $('#pattern_plot').attr('src', "");
            $('#pattern_plot').attr('src', "/ajax/plot-pattern-png/?pat_num=" + pat_num //TODO przerob na ajaxa loader
            +"&data_id=" + data_id
            +"&movie_number=" + movie_number
            +"&ele_to_plot=" + ele_to_plot
            +"&neighbours=" + neighbours
            +"&y_axis_min=" + y_axis_min
            +"&y_axis_max=" + y_axis_max
            +"&x_axis_min=" + x_axis_min
            +"&x_axis_max=" + x_axis_max);
        }
    }

    $("#pattern_data").change(function () {
        $(function () {
          var url = $("#single_pattern_plot").attr("data-pattern-url")

          $.ajax({
            url: url,
            data: {
                'data_id': $("#pattern_data").val()

            },
            success: function (data) {
              $("#pattern_number").html(data);
            }
          });
        });
    });

    $("#neigh").change(function(){
        plot()
    });

    $("#pattern_number").change(function () {
        $(function () {
          var url = $("#single_pattern_plot").attr("data-movie-for-pattern-url")

          $.ajax({
            url: url,
            data: {
                'pat_num': $("#pattern_number").val(),
                'data_id': $("#pattern_data").val()
            },
            success: function (data) {
              $("#movie_for_pattern").html(data);
            }
          });
        });
    });

    $(function () {
      var url = $("#single_pattern_plot").attr("data-dataxxx-url")
      var exp_id = '{{ pk }}';
      $.ajax({
        url: url,
        data: {
          'exp_id': exp_id
        },
        success: function (data) {
          $("#pattern_data").html(data);
        }
      });
    });

    $('#next_plot').click(function() {
        $('#movie_for_pattern option:selected').next().prop('selected', true);
        plot()
    });

    $('#previous_plot').click(function() {
        $('#movie_for_pattern option:selected').prev().prop('selected', true);
        plot()
    });

    $("#matrix").click(function(){
    var h= screen.height;
    var w= screen.width;
    window.open("/static/retina/matryca.png", '_blank' , 'width='+w+', height='+h+'');
    });

    function isNormalInteger(str) {
        var n = Math.floor(Number(str));
        return n !== Infinity && String(n) === str;// TODO export to general functions
    }
    $( "#pattern_plot_button" ).click(plot);

</script>

{% endblock %}


{% block content %}

<h2>Plot data for single pxmy file:</h2>

<div id="dataForm"  data-pxmy-url="{% url 'ajax_load_pxmy' %}"
                    data-dataxxx-url="{% url 'ajax_load_dataxxx' %}"
                    data-pattern-url="{% url 'ajax_load_pattern' %}"

     novalidate>
    {% csrf_token %}
    <table>
        <tbody>
        <tr>
            <th><label for="id_data">Data:</label></th>
            <td><select name="data" required="" id="id_data">
                <option value="null">---------</option>
            </select></td>
        </tr>
        <tr>
            <th><label for="id_px_my">Px my:</label></th>
            <td><select name="px_my" required="" id="id_px_my">
            </select></td>
        </tr>
        <tr>
            <th><label for="id_pattern_file">Pattern file:</label></th>
            <td><p id="id_pattern_file"></p></td>
        </tr>
        <tr>
            <th><label for="electrode_number_min">Electrode number from:</label></th>
            <td><input type="text" name="Electrode number from" maxlength="100" required="" id="electrode_number_min"></td>
        </tr>
        <tr>
            <th><label for="electrode_number_max">Electrode number to:</label></th>
            <td><input type="text" name="Electrode number to" maxlength="100" required="" id="electrode_number_max"></td>
        </tr>
        <tr>
            <th><button id="plot_button">Plot</button></th>

        </tr>
        </tbody>
    </table>
    <th colspan="2"><label class="error-msg" id="error_label"></label></th>


</div>
<div id='single-plot' class="plot-div">
    <img id="plot" class="plot-size">
</div>

<script>
    $("#id_data").change(function () {
        $(function () {
          var url = $("#dataForm").attr("data-pxmy-url")

          $.ajax({
            url: url,
            data: {
                'data_id': $("#id_data").val()
            },
            success: function (data) {
              $("#id_px_my").html(data);
            }
          });
        });
    });

    $("#id_px_my").change(function () {
        $(function () {

          var url = $("#dataForm").attr("data-pattern-url")

          $.ajax({
            url: url,
            data: {
                'pxmy_id': $("#id_px_my").val()
            },
            success: function (data) {
              $("#id_pattern_file").html(data);
            }
          });
        });
    });

    $(function () {
      var url = $("#dataForm").attr("data-dataxxx-url")
      var exp_id = '{{ pk }}';
      $.ajax({
        url: url,
        data: {
          'exp_id': exp_id
        },
        success: function (data) {
          $("#id_data").html(data);
        }
      });
    });

    function isNormalInteger(str) {
        var n = Math.floor(Number(str));
        return n !== Infinity && String(n) === str;
    }
    $( "#plot_button" ).click(function() {
        var elect_min = $("#electrode_number_min").val();
        var elect_max = $("#electrode_number_max").val();
        var id_pxmy = $("#id_px_my").val()
        $('div#single-plot').show();

        if (!isNormalInteger(elect_min)){
            $("#error_label").html("ERROR!: 'Electrode number from' is not a number!");
        }

        else if (!isNormalInteger(elect_max)){
            $("#error_label").html("ERROR!: 'Electrode number to' is not a number!");
        }

        else if (elect_min > 512 || elect_max > 512 || elect_min < 1 || elect_max < 1){ //TODO 512 import from static
            $("#error_label").html("ERROR!: Electrode number out of range. Must be beetween <1, 512>!");
        }

        else if (id_pxmy == null || id_pxmy == 'null') {
            $("#error_label").html("ERROR!: 'Px my' is not selected!");
        }

        else if (parseInt(elect_min) > parseInt(elect_max)){
            $("#error_label").html("ERROR!: 'Electrode number from' is bigger than 'Electrode number to'!");
        } else{
            $("#error_label").html("");
            $('#plot').attr('src', "");
            $('#plot').attr('src', "/ajax/plot-png/?rawdata_id="+id_pxmy
            +"&electrode_from="+elect_min
            +"&electrode_to="+elect_max);
        }
    });

</script>

{% endblock %}